CREATE DATABASE chatInfo;
USE chatInfo;

CREATE TABLE users (
  'id'  INT NOT NULL AUTO_INCREMENT,
  'name' VARCHAR(200) NOT NULL,
  'password' VARCHAR(200) NOT NULL,
  PRIMARY KEY('id')
);

CREATE TABLE messages (
  'id' INT NOT NULL AUTO_INCREMENT,
  'roomID' INT NOT NULL AUTO_INCREMENT,
  'name' VARCHAR(200) NOT NULL,
  'content' VARCHAR(200) NOT NULL
  PRIMARY KEY('id')
);

CREATE TABLE rooms (
  'id' INT NOT NULL AUTO_INCREMENT,
  'name' VARCHAR(200) NOT NULL,
  PRIMARY KEY('id')
);