CREATE DATABASE chatInfo;
USE chatInfo;

CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE messages (
  id INTEGER NOT NULL AUTO_INCREMENT,
  roomID INTEGER,
  name VARCHAR(200) NOT NULL,
  content VARCHAR(200) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE rooms (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  PRIMARY KEY(id)
);